config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root :to => 'home#index'
  resources :projects

  get 'about', :to => 'home#about'
  get 'contact', to: 'messages#new', as: 'new_message'
  post 'contact', to: 'messages#create', as: 'create_message'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message
  include ActiveModel::Model
  attr_accessor :name, :email, :body, :subject
  validates :name, :email, :body, :subject, presence: true
end

app/models/project.rb
class Project < ApplicationRecord
  validates :title, :presence => true
  validates :title, :uniqueness => true
  validates :description, :presence => true

  has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/

private
  def set_s3_direct_post
    @s3_direct_post = S3_BUCKET.presigned_post(key: "uploads/#{SecureRandom.uuid}/${filename}", success_action_status: '201', acl: 'public-read')
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end

  def about

  end

  def contact

  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)

    if @message.valid?
      MessageMailer.contact_me(@message).deliver_now
      redirect_to new_message_path, notice: "Message received!"
    else
      flash[:alert] = @message.errors.full_messages.join(' -- ')
      render :new
    end
  end

  private

  def message_params
    params.require(:message).permit(:name, :email, :body, :subject)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_s3_direct_post, only: [:new, :edit, :create, :update]
  def index
    @projects = Project.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/about.html.erb
<body id="aboutBack">
  <div class="card">
    <h4>About</h4>
    <div class="row">
      <div class="col-sm-12">
        <div id="profPic">
          <img src="/images/profile.jpg" alt="Profile Picture">
        </div>
        <p>Junior developer with an eclectic background excited for the long road of learning that programming offers. I’ve owned my own company which showed me the importance of being self-motivated, crewing on boats made me resilient to changing conditions and challenging schedules, and as team-lead of four CNA’s I learned a lot about working with and managing diverse groups of people. All of these experiences have given me confidence, desire to learn, and a strong work ethic that I still foster to this day.</p>
        <p>When I'm not sitting at my desk coding; I might be sailing, rock-climbing, or making music. As a developer my strengths are in spotting patterns and finding solutions to problems. I first started coding in March 2017. In July I started the Ruby/Rails track at <a href="https://www.epicodus.com/" target="_blank">Epicodus</a> in Portland OR. There we built apps using a variety of languages and tools with a test-driven focus.</p>
        <p>I've also had the opportunity to work on several group projects which has taught me to work productively on a team and good practice using Git for organizing work flow. Thanks for visiting my site. Head over to the projects section to see some of my work or the contact page to get in touch.</p>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col-sm-4">
        <img class="profPics" src="/images/cat.jpg" alt="Profile Picture">
      </div>
      <div class="col-sm-4">
        <img class="profPics" src="/images/cliff.jpg" alt="Profile Picture">
      </div>
      <div class="col-sm-4">
        <img class="profPics" src="/images/shoes.jpg" alt="Profile Picture">
      </div>
    </div>
  </div>
</body>

app/views/home/index.html.erb
<body id="homeBack">
  <div id="splash">
    <h1>David Hale</h1>
    <h3>- 1987 -</h3>
    <br>
    <i class="devicon-javascript-plain"></i>
    <i class="devicon-nodejs-plain-wordmark"></i>
    <i class="devicon-nodewebkit-plain-wordmark"></i>
    <i class="devicon-jquery-plain-wordmark"></i>
    <i class="devicon-angularjs-plain-wordmark"></i>
    <i class="devicon-typescript-plain"></i>
    <i class="devicon-jasmine-plain-wordmark"></i>
    <i class="devicon-html5-plain"></i>
    <i class="devicon-css3-plain"></i>
    <i class="devicon-bootstrap-plain"></i>
    <i class="devicon-ruby-plain"></i>
    <i class="devicon-rails-plain-wordmark"></i>
    <i class="devicon-postgresql-plain-wordmark"></i>
    <i class="devicon-bower-line-wordmark"></i>
    <i class="devicon-heroku-plain-wordmark"></i>
    <i class="devicon-gulp-plain"></i>
    <i class="devicon-github-plain"></i>
    <i class="devicon-git-plain-wordmark"></i>
    <i class="devicon-slack-plain"></i>
    <i class="devicon-atom-original"></i>
  </div> <!--/id="splash" -->
</body>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div class="card">
    <h3>Please fix these errors:</h3>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://cdn.rawgit.com/konpa/devicon/df6431e323547add1b4cf45992913f15286456d3/devicon.min.css">
    <script src="https://use.fontawesome.com/612c5de416.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <style>
    @import url('https://fonts.googleapis.com/css?family=Titillium+Web');
  </style>

  <header>
    <%= link_to('Home', root_path) %> |
    <%= link_to('About', about_path) %> |
    <%= link_to('Projects', projects_path) %> |
    <%= link_to('Contact', new_message_path) %>
    <h3 id='name'>David Hale</h3>
  </header>
  <br><br><br>
  <body>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class='alert alert-dismissible fade show card alertCard' role='alert'>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <li aria-hidden="true">&times;</li>
          </button>
          <%= value %>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
  <footer id='navbar-footer'>
    <small>©2018 - David Hale</small>
    <small>
      <% if user_signed_in? %>
        <%= link_to('Admin', rails_admin_path)  %> <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
      <% else %>
        <%= link_to('Site Admin', rails_admin_path) %>
      <% end %>
    </small>
  </footer>
</html>

app/views/messages/new.html.erb
<body id="contactBack">
  <div class="card">
    <div class="row">
      <div class="col-md-7">
        <h4>Contact</h4>
        <p>Thanks for visiting my site! Please send me a meessage if you have any questions about my experience, availability, projects, or to request a resume. You can also challenge me to a game of chess, provide book recommendations, or just say <em>"Hello"</em>. If filling out forms isn't your thing then click on the social media icon of your choice below. I look forward to hearing from you.</p>
        <hr>
        <div id="mediaButtons">
          <a target="_blank" href="https://www.linkedin.com/in/david-hale-a5756a13a/" class="fa fa-lg fa-linkedin"></a>
          <a target="_blank" href="https://github.com/phuzisham" class="fa fa-lg fa-github"></a>
          <a target="_blank" href="https://www.instagram.com/phuzisham/" class="fa fa-lg fa-instagram"></a>
          <a target="_blank" href="https://www.facebook.com/david.hale.771" class="fa fa-lg fa-facebook"></a>
          <a target="_blank" href="https://twitter.com/phuzisham" class="fa fa-lg fa-twitter"></a>
        </div>
      </div>
      <div class="col-md-5">
        <%= form_for @message, url: create_message_url do |f| %>
          <div class="field">
            <%= f.text_field :name, placeholder: 'name', style: 'width:55%;', class: 'formBack' %>
          </div>
          <br>
          <div class="field">
            <%= f.email_field :email, placeholder: 'email', style: 'width:55%;', class: 'formBack' %>
          </div>
          <br>
          <div class="field">
            <%= f.text_field :subject, placeholder: 'subject', style: 'width:55%;', class: 'formBack' %>
          </div>
          <br>
          <div class="field">
            <%= f.text_area :body, placeholder: 'body', :rows => 5, style: 'width:100%;', class: 'formBack' %>
          </div>
          <br>
          <div class="field">
            <%= f.submit 'Send Message', class: 'btn' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</body>

app/views/projects/index.html.erb
<body id="projectsBack">
  <% if @projects.any? %>
    <div class="card">
      <% @projects.each do |p| %>
        <div class="row">
          <div class="col-sm-12">
            <div class="projectTitle">
              <h3><%= p.title %></h3>
              <h5><%= p.language %></h5>
              <a target='_blank' href='<%= p.link %>'>GitHub Repository</a>
            </div>
            <p><%= p.description %></p>
            <div class="projectImage">
              <%= image_tag(p.photo.url(:original)) %>
            </div>
          </div>
        </div>
        <hr>
      <% end %>
    </div>
  <% else %>
    <div class="card">
      <h4>No projects yet.</h4>
    </div>
  <% end %>
</body>